WebApplication1/Models/Extended/User.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.ComponentModel.DataAnnotations;
//using System.Runtime.Remoting.Lifetime;

//namespace WebApplication1.Models
//{
//    [MetadataType(typeof(UserForm))]
//    public  partial class User
//    {
//        public  string ConfirmPassword { get; set; }
//    }

//    public class UserForm
//    {

//        public int UserId { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "Username is Required")]
//        [Display(Name = "Username")]
//        public string Username { get; set; }

//        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is Required")]
//        [Display(Name = "Password")]
//        [DataType(DataType.Password)]
//        [MinLength(8,ErrorMessage = "Must be at least 8 characters")]
//        public string PasswordHash { get; set; }

//        [Display(Name = "Confirm Password")]
//        [Required(AllowEmptyStrings = false, ErrorMessage = " Confirm Password is Required")]
//        [MinLength(8, ErrorMessage = "Must be at least 8 characters")]
//        [DataType(DataType.Password)]
//        [Compare("PasswordHash", ErrorMessage = "Password does not match")]
//        public string ConfirmPassword { get; set; }

//        [Display(Name = "Email")]
//        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is required")]
//        [EmailAddress(ErrorMessage = "Invalid Email Address")]
//        public string Email { get; set; }
//        public Nullable<System.DateTime> CreatedDate { get; set; } = DateTime.Now;
//        public Nullable<bool> IsActive { get; set; } = true;
//        public string ResetPasswordCode { get; set; }
//        public Nullable<int> DEPT_ID { get; set; } = 1;

//        public DateTime? ResetPasswordExpiry { get; set; }

//        public virtual DEPT DEPT { get; set; }
//    }
//}

WebApplication1/Models/ResetPassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class ResetPassword
    {
        [Required]
        public string ResetCode { get; set; }

        [Required(ErrorMessage = "New Password required", AllowEmptyStrings = false)]
        [StringLength(255, MinimumLength = 8, ErrorMessage = "Must be at least 8 characters.")]
        [DataType(DataType.Password)]

        public string PasswordHash { get; set; }

        [Required(ErrorMessage = "Confirm Password required", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [Compare("PasswordHash", ErrorMessage = "Password does not match")]
        //[StringLength(255, MinimumLength = 8, ErrorMessage = "Must be at least 8 characters.")]
        public string ConfirmPassword { get; set; }

    }
}

WebApplication1/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string ConfirmPassword { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; } = DateTime.Now;
        public Nullable<bool> IsActive { get; set; } = true;
        public string ResetPasswordCode { get; set; }
        public Nullable<int> DEPT_ID { get; set; } = 1;

        public System.Guid ActivationCode { get; set; }

        public DateTime? ResetPasswordExpiry { get; set; }
        public bool IsEmailVerified { get; set; }
    
        public virtual DEPT DEPT { get; set; }
    }
}

WebApplication1/Controllers/MOVEHISTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class MOVEHISTsController : Controller
    {
        private MyStartDBEntities db = new MyStartDBEntities();

        // GET: MOVEHISTs
        public ActionResult AuditLog()
        {
            if (Session["Username"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            return View(db.MOVEHISTs.ToList());
        }

        // GET: MOVEHISTs/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOVEHIST mOVEHIST = db.MOVEHISTs.Find(id);
            if (mOVEHIST == null)
            {
                return HttpNotFound();
            }

            return View(mOVEHIST);
        }

        // GET: MOVEHISTs/Create
        public ActionResult Create()
        {
            return View();
        }

    }
}

WebApplication1/Controllers/UsersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.NetworkInformation;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Security.Principal;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    //[Authorize]
    public class UsersController : Controller
    {
        private MyStartDBEntities db = new MyStartDBEntities();

        // GET: Users

        public ActionResult Index()
        {
            if (Session["Username"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            return View(db.Users.ToList());
        }



        // GET: Users/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);
            if (user == null)
            {
                return View("NotFound");
            }

            if (Session["Username"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            return View(user);
        }

        // GET: Users/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Username,PasswordHash,ConfirmPassword,Email,CreatedDate,IsActive,ActivationCode,IsEmailVerified")] User user)
        {

            bool Status = false;
            string message = "";
            try
            {
                using (var connection = new SqlConnection(WebConfigurationManager.ConnectionStrings["MySqlConnection"].ConnectionString))
                {
                    connection.Open();


                    if (connection.State == ConnectionState.Open)
                    {
                        // Success (connection opened)
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Connection Error! Invalid Database";
                        return View();
                    }
                }
            }
            catch (SqlException)
            {
                Response.Write("<script>alert('Wrong Connection Error! Invalid Database')</script>");
                return View();
            }

            if (ModelState.IsValid)
            {
                // Check if email already exists
                if (db.Users.Any(x => x.Email == user.Email))
                {
                    ModelState.AddModelError("Email", "Email Already Registered");
                    return View(user);
                }

                // Check if username already exists
                if (db.Users.Any(x => x.Username == user.Username))
                {
                    ModelState.AddModelError("Username", "Username Already Registered");
                    return View(user);
                }

                // Check for empty fields
                if (string.IsNullOrWhiteSpace(user.Username) || string.IsNullOrWhiteSpace(user.Email) || string.IsNullOrWhiteSpace(user.PasswordHash))
                {


                    if (string.IsNullOrEmpty(user.Username))
                    {
                        ModelState.AddModelError("Username", "Username field is empty");
                    }
                    if (string.IsNullOrEmpty(user.Email))
                    {
                        ModelState.AddModelError("Email", "Email field is empty");
                    }
                    if (string.IsNullOrEmpty(user.PasswordHash))
                    {
                        ModelState.AddModelError("PasswordHash", "Password field is empty");
                    }
                    else if (user.PasswordHash.Length < 8)
                    {
                        ModelState.AddModelError("PasswordHash", "Must be at least 8 characters");
                    }
                    if (string.IsNullOrEmpty(user.ConfirmPassword))
                    {
                        ModelState.AddModelError("ConfirmPassword", "Confirm Password field is empty");
                    }
                    else if (user.ConfirmPassword.Length < 8)
                    {
                        ModelState.AddModelError("ConfirmPassword", "Must be at least 8 characters");
                    }

                    return View();
                }

                if (user.PasswordHash.Length < 8)
                {
                    ModelState.AddModelError("PasswordHash", "Must be at least 8 characters");
                    //ModelState.AddModelError("ConfirmPassword", "Must be at least 8 characters");
                    return View(user);
                }


                if (user.DEPT_ID == null)
                {
                    TempData["deptEmpty"] = true;
                }

                // Check if passwords match
                if (user.PasswordHash == user.ConfirmPassword)
                {

                    #region Password Hashing
                    user.PasswordHash = Hashing.Hash(user.PasswordHash);
                    user.ConfirmPassword = Hashing.Hash(user.ConfirmPassword);
                    #endregion
                    user.IsEmailVerified = false;
                    user.CreatedDate = DateTime.Now;
                    user.IsActive = true;


                    #region Generate Activation Code
                    user.ActivationCode = Guid.NewGuid();
                    #endregion
                    
                    //
                    //Add User
                  
                        db.Users.Add(user);
                        db.SaveChanges();

                        //Send Email to User
                        SendVerificationLink(user.Email, user.ActivationCode.ToString());
                   

                    //MAC ADDRESS
                    var macAddr = (from nic in NetworkInterface.GetAllNetworkInterfaces()
                                   where nic.OperationalStatus == OperationalStatus.Up
                                   select nic.GetPhysicalAddress().ToString()).FirstOrDefault() ?? "Unknown";


                    //Audit Logs
                    //Start Audit
                    var user_id = user.UserId;
                    var audit = new MOVEHIST
                    {
                        Id = user_id,
                        OLD_DATA = $"Username={user.Username}, Email={user.Email}",
                        NEW_DATA = $"Username={user.Username}, Email={user.Email}",
                        D_ACTION = DateTime.Now.ToString("MM/dd/yyyy"),
                        T_ACTION = DateTime.Now.ToString("HH:mm:ss"),
                        DESCRIPTION = "User creation",
                        ACTION_BY = user.Username,
                        MAC_ADDRESS = macAddr,
                        TYPE = "Account Creation",
                        NEW_SAL = "0",
                        OLD_SAL = "0"
                    };

                    // Add and save the audit record
                    db.MOVEHISTs.Add(audit);
                    db.SaveChanges();
                    //End Audit

                    TempData["UserCreate"] = 
                    $@"<script>
                        Swal.fire({{
                        icon: 'success',
                        title: 'Account Creation Success!',
                        html: 'Account activation link has been sent to your Email: {user.Email}'
                        }});
                    </script>";
                    return RedirectToAction("Login");

                }
                else
                {
                    ModelState.AddModelError("ConfirmPassword", "Password does not match");
                    
                    return View(user);
                }

            }

            return View(user);
        }

        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;

            using (MyStartDBEntities db = new MyStartDBEntities())
            {
                //avoid Confirmpassword does not match issue on save changes
                db.Configuration.ValidateOnSaveEnabled = false;

                var verAccount = db.Users.Where(x => x.ActivationCode == new Guid(id)).FirstOrDefault();

                if (verAccount != null)
                {
                    verAccount.IsEmailVerified = true;
                    db.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }

            }
            ViewBag.Status = true;
            return View();
        }


        // GET: Users/Edit/5

        public ActionResult Edit(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);
            if (user == null)
            {
                //return HttpNotFound();
                return View("NotFound");
            }

            if (Session["Username"] == null)
            {
                return RedirectToAction("Login", "Users");
            }



            user.ConfirmPassword = user.PasswordHash;

            PopulateDropDown();

            return View(user);
        }

        //POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]

WebApplication1/Views/Users/Delete.cshtml
@model WebApplication1.Models.User

@{
    ViewBag.Title = "Delete";
}

<div id="loader" class="loader"></div>

<div class="form-horizontal d-flex p-5 flex-column">
    <div class="m-auto bg-warning text-center p-3 mb-2 rounded">
        <h4 class="m-0">Are you sure you want to DELETE</h4>
        <h4 class="m-0"> User: <i><u>@Html.DisplayFor(model => model.Username)</u></i> ?</h4>
    </div>

    <div class="d-flex flex-column m-auto">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                Date Created
                @*@Html.DisplayNameFor(model => model.CreatedDate)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger px-4 mx-3" id="btDelete" />
                @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-outline-primary mx-3 px-4" })
            </div>
        }
    </div>
</div>


<script>

    var btDelete = document.getElementById("btDelete");

    btDelete.addEventListener('click', function (e) {
        e.preventDefault();
        var form = $(this).parents('form');
        Swal.fire({
            title: 'Delete this User?',
            text: 'This account will be permanently deleted!',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Delete User'
        }).then((result) => {
            if (result.value) {
                showLoading();
                form.submit();
            }
        });
    });

    function showLoading() {
        event.preventDefault();
        $(".loader").removeClass("hidden");
        return true;
    }

    document.addEventListener("DOMContentLoaded", function () {
        loader.setAttribute("class", "hidden");
    });

</script>

WebApplication1/Views/Users/LinkExpired.cshtml
@{
    ViewBag.Title = "Link Expired";
    Layout = "~/Views/Shared/_LayoutNoSession.cshtml";
}

<div class="container text-center mt-5">
    <div class="alert alert-warning" role="alert">
        <h1 class="display-4">Link Expired</h1>
        <p class="lead">The reset password link has expired. Please request a new link.</p>
    </div>

</div>

WebApplication1/Views/Users/Reports.cshtml
@model IEnumerable<WebApplication1.Models.User>

@{
    ViewBag.Title = "Reports";
}

<div class="form-horizontal d-flex flex-column p-5">
    <h2 class="text-center">Reports</h2>

    <hr />
    <table id="tblUsers" class="table table-bordered table-striped table-light small">
        <thead>
            <tr>
                <th>@Html.DisplayName("ID")</th>
                <th>@Html.DisplayName("USERNAME")</th>
                <th>@Html.DisplayName("EMAIL")</th>
                <th>@Html.DisplayName("DATE_CREATED")</th>
                <th>@Html.DisplayName("ISACTIVE")</th>
                <th>@Html.DisplayName("Department")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.UserId)</td>
                    <td>@Html.DisplayFor(modelItem => item.Username)</td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@Html.DisplayFor(modelItem => item.CreatedDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.IsActive)</td>
                    <td>@Html.DisplayFor(modelItem => item.DEPT.DEPT1)</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>@Html.DisplayName("ID")</th>
                <th>@Html.DisplayName("USERNAME")</th>
                <th>@Html.DisplayName("EMAIL")</th>
                <th>@Html.DisplayName("DATE_CREATED")</th>
                <th>@Html.DisplayName("ISACTIVE")</th>
                <th>@Html.DisplayName("Department")</th>
            </tr>
        </tfoot>
    </table>

    <p class="mx-auto">
        @Html.ActionLink("Audit Log", "AuditLog", "MOVEHISTs", new { area = "" }, new { @class = "btn btn-outline-primary" })
    </p>
</div>

@*Table Design and Features Imports*@

<link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>

@*Excel Export*@

<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

@*PDF Export*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

@*Export Button Features*@

<script src="https://cdn.datatables.net/buttons/3.2.0/js/dataTables.buttons.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.0/js/buttons.html5.min.js"></script>

@*Search Panes*@
<script src="https://cdn.datatables.net/searchpanes/2.3.3/js/dataTables.searchPanes.js"></script>
<script src="https://cdn.datatables.net/searchpanes/2.3.3/js/searchPanes.dataTables.js"></script>

@*Selecting Data Tables*@
<script src="https://cdn.datatables.net/select/2.1.0/js/dataTables.select.js"></script>
<script src="https://cdn.datatables.net/select/2.1.0/js/select.dataTables.js"></script>

<!-- Alerts -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script nonce="myScript">
    var tbId = document.getElementById('tbId');
    var tbMac = document.getElementById('tbMac');
    var tbType = document.getElementById('tbType');
    var tbOld = document.getElementById('tbOld');
    var tbNew = document.getElementById('tbNew');
    var tbDate = document.getElementById('tbDate');
    var tbTime = document.getElementById('tbTime');
    var tbBy = document.getElementById('tbBy');
    var tbUid = document.getElementById('tbUid');

    $(document).ready(function () {
        new DataTable('#tblAudit', {
            layout: {
                top: 'pageLength',
                topStart: {
                    buttons: [

                        { extend: 'excel', className: 'btn btn-outline-success btn-sm px-3 py-2' },
                        { extend: 'pdf', orientation: 'landscape', className: 'btn btn-outline-danger btn-sm px-3 py-2 mx-1' }

                    ],
                },
            },

            initComplete: function () {
                //Action ID Filter
                this.api()
                    .columns([0])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--Audit ID--</option></select>')
                            .appendTo($('#tbId').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //MAC Address Filter
                this.api()
                    .columns([1])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--MAC Address--</option></select>')
                            .appendTo($('#tbMac').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //Action Type Filter
                this.api()
                    .columns([2])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--Action Type--</option></select>')
                            .appendTo($('#tbType').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //Date Action Filter
                this.api()
                    .columns([7])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--Date Action--</option></select>')
                            .appendTo($('#tbDate').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //Input Type Sorting
                //this.api()
                //    .columns([7])
                //    .every(function () {
                //        var column = this;
                //        var date = column.header().textContent;

                //        // Create input element
                //        var input = document.createElement('input');
                //        input.placeholder = date;
                //        input.className = "text-justify";
                //        tbDate.replaceChildren(input);

                //        // Event listener for user input
                //        input.addEventListener('keyup', () => {
                //            if (column.search() !== this.value) {
                //                column.search(input.value).draw();
                //            }
                //        });
                //    });

                //Time Action Filter
                this.api()
                    .columns([8])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--Time Action--</option></select>')
                            .appendTo($('#tbTime').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //Action By Filter
                this.api()
                    .columns([10])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--Action By--</option></select>')
                            .appendTo($('#tbBy').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });

                //UID Filter
                this.api()
                    .columns([11])
                    .every(function () {
                        var column = this;
                        var type = column.header().textContent;

                        var select = $('<select class="form-control form-control-sm"><option value="">--User ID--</option></select>')
                            .appendTo($('#tbUid').empty())
                            .on('change', function () {
                                if (column.search() !== this.value) {
                                    column.search(this.value).draw();
                                }

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            var val = $('<div/>').html(d).text();
                            select.append('<option value="' + val + '">' + val + '</option>');
                        });
                    });
            }
        });

    });</script>